import { Octokit } from '@octokit/rest';
import { run, redact, runOrThrow } from '../exec.js';
import { configureGitCredentials, currentBranch, hasUncommittedChanges } from '../git.js';
import { loadConfig, requireToken } from '../config.js';
import type { PhaseResult, StepLog } from '../result.js';

function splitFullName(fullName: string): { owner: string; repo: string } {
  const [owner, repo] = fullName.split('/');
  if (!owner || !repo) {
    throw new Error(`REPO_FULL_NAME must be in "owner/repo" form, received "${fullName}"`);
  }
  return { owner, repo };
}

async function findExistingPullRequest(
  octokit: Octokit,
  owner: string,
  repo: string,
  branchName: string,
): Promise<string | undefined> {
  const existing = await octokit.pulls.list({
    owner,
    repo,
    head: `${owner}:${branchName}`,
    state: 'open',
  });
  return existing.data[0]?.html_url;
}

export async function publish(): Promise<PhaseResult> {
  const config = loadConfig();
  const token = requireToken();
  const steps: StepLog[] = [];

  await configureGitCredentials(token, config.repoUrl);

  if (!(await hasUncommittedChanges(config.repoDir))) {
    steps.push({
      step: 'PR',
      output: 'The codemod produced no changes, so no pull request was opened.',
    });
    return { phase: 'publish', ok: true, steps, data: { skipped: true } };
  }

  const baseBranch = await currentBranch(config.repoDir);

  // -B and a force push keep BullMQ retries idempotent against a branch left
  // behind by an earlier attempt.
  await runOrThrow('git', ['checkout', '-B', config.branchName], { cwd: config.repoDir });
  await runOrThrow('git', ['add', '--all'], { cwd: config.repoDir });

  const commitMessage = `chore: migrate ${config.dependencyName} to ${config.targetVersion}`;
  await runOrThrow('git', ['commit', '-m', commitMessage], { cwd: config.repoDir });

  const push = await run(
    'git',
    ['push', '--force', 'origin', `HEAD:refs/heads/${config.branchName}`],
    { cwd: config.repoDir },
  );

  if (push.code !== 0) {
    steps.push({ step: 'PR', output: redact(push.output, [token]), exitCode: push.code });
    return { phase: 'publish', ok: false, error: 'git push failed', steps };
  }

  const { owner, repo } = splitFullName(config.repoFullName);
  const octokit = new Octokit({ auth: token, baseUrl: config.githubApiUrl });

  let pullRequestUrl: string | undefined;

  try {
    const created = await octokit.pulls.create({
      owner,
      repo,
      title: `Migrate ${config.dependencyName} to ${config.targetVersion}`,
      head: config.branchName,
      base: baseBranch,
      body: [
        `Automated migration of \`${config.dependencyName}\` to \`${config.targetVersion}\`.`,
        '',
        'Generated by SyncLab. The test suite passed inside an isolated sandbox before this pull request was opened.',
      ].join('\n'),
    });
    pullRequestUrl = created.data.html_url;
  } catch (error: unknown) {
    pullRequestUrl = await findExistingPullRequest(octokit, owner, repo, config.branchName);
    if (!pullRequestUrl) {
      throw error;
    }
  }

  steps.push({
    step: 'PR',
    output: `Pushed ${config.branchName} onto ${baseBranch} and opened ${pullRequestUrl}`,
  });

  return { phase: 'publish', ok: true, steps, data: { pullRequestUrl, branchName: config.branchName } };
}
